import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import PhoneInput from 'react-phone-input-2'
import React, { useState } from "react";
import 'react-phone-input-2/lib/style.css'
import Link from 'next/link';
export default function Home() {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>threshold</title>
        <meta name="description" content="Generated by create next app v " />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to threshold
        </h1>

        <p className={styles.description}>
          Get started education in virtual
          
         </p>
          <div className={styles.carda}> 
            <div className={styles.student}>
              <a href="/login">student</a>
            </div>
            <div className={styles.teacher}>
              <a href="/login">teacher</a>
            </div>
            <div className={styles.administrator}>
              <a href="/login">administrator</a>
            </div>
          </div>
         {/* <a href="/login">login</a> */}
      </main>

      
    </div>
  )
}
